name: hecstac
channels:
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.12  # or whichever version you use
  - affine=2.4.0
  - aiobotocore=2.21.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.14
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - boto3=1.37.1
  - botocore=1.37.1
  - certifi=2025.7.14
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - contextily=1.6.2
  - contourpy=1.3.2
  - coverage=7.9.2
  - cycler=0.12.1
  - distlib=0.4.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - filelock=3.18.0
  - fonttools=4.59.0
  - frozenlist=1.7.0
  - fsspec=2025.3.1
  - geographiclib=2.0
  - geopandas=1.0.1
  - geopy=2.4.1
  - h5py=3.14.0
  - identify=2.6.12
  - idna=3.10
  - jmespath=1.0.1
  - joblib=1.5.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - kiwisolver=1.4.8
  - markdown-it-py=3.0.0
  - matplotlib=3.8.4  # Changed to resolve xarray conflict
  - mdurl=0.1.2
  - mercantile=1.2.1
  - multidict=6.6.3
  - mypy-boto3-s3=1.39.5
  - networkx=3.4.2
  - nodeenv=1.9.1
  - numpy=1.26.4
  - obstore=0.6.0
  - openpyxl=3.1.5
  - packaging=25.0
  - pandas=2.3.1
  - pillow=11.3.0
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - pre-commit=4.2.0
  - pygments=2.19.2
  - pyogrio=0.11.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pystac=1.13.0
  - pytest=8.4.1
  - pytest-cov=6.2.1
  - pytest-json-report=1.5.0
  - pytest-metadata=3.1.1
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - rasterio=1.4.3
  - referencing=0.36.2
  - requests=2.32.3
  - rich=14.0.0
  - rpds-py=0.26.0
  - ruff=0.12.4
  - s3fs=2025.3.1
  - s3transfer=0.11.3
  - shapely=2.0.7
  - six=1.17.0
  - tomli=2.2.1
  - typing_extensions=4.14.1
  - tzdata=2025b
  - urllib3=2.5.0
  - virtualenv=20.32.0
  - wrapt=1.17.2
  - xarray=2025.6.1
  - xyzservices=2025.4.0
  - yarl=1.20.1

  # pip-only packages
  - pip
  - pip:
      - cfgv>=3.4.0
      - dotenv>=0.9.9
      - fiona>=1.10.0rc1
      - hydrostab>=0.2.0
      - iniconfig>=2.1.0
      - propcache>=0.3.2
      - pyarrow>=21.0.0
      - rashdf>=0.10.0
      - rasqc>=0.0.3
      - -e .
